# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
